In [72]:
import pandas as pd
import numpy as np 
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [8]:
df= pd.read_csv('spam.csv', encoding= "latin1")

In [9]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN


In [11]:
df.v1.value_counts()

v1
ham     4825
spam     747
Name: count, dtype: int64

In [26]:
df.pop('Unnamed: 4')

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ... 
5567    NaN
5568    NaN
5569    NaN
5570    NaN
5571    NaN
Name: Unnamed: 4, Length: 5572, dtype: str

In [27]:
df.head()

,v1,v2
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [29]:
df.v1.value_counts()/len(df)*100

v1
ham     86.593683
spam    13.406317
Name: count, dtype: float64

In [32]:
df['spam']= df['v1'].apply(lambda x: 1 if x=='spam' else 0)

In [33]:
df.head()

,v1,v2,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [34]:
df.shape

(5572, 3)

Train Test split

In [39]:
x_train, x_test, y_train, y_test =train_test_split(df.v2, df.spam,test_size=0.2)

In [40]:
x_test.shape

(1115,)

In [42]:
x_train[: 4]

979     Another month. I need chocolate weed and alcohol.
3014     &lt;#&gt;  mins but i had to stop somewhere f...
3259    I'm always looking for an excuse to be in the ...
1743                     I love to wine and dine my lady!
Name: v2, dtype: str

In [43]:
y_train[:4]

979     0
3014    0
3259    0
1743    0
Name: spam, dtype: int64

Create bag of words representation using CountVectorizer

In [85]:
v=CountVectorizer()
x_train_cv=v.fit_transform(x_train.values)
#x_test_cv=v.transform(x_test)

In [48]:
x_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59553 stored elements and shape (4457, 7767)>

In [49]:
x_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7767,))

In [50]:
x_train_cv.shape

(4457, 7767)

In [80]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'ûªve', 'ûò', 'ûówell'],
      shape=(7767,), dtype=object)

In [56]:
v.vocabulary_

{'another': 988,
 'month': 4591,
 'need': 4745,
 'chocolate': 1824,
 'weed': 7450,
 'and': 970,
 'alcohol': 907,
 'lt': 4265,
 'gt': 3281,
 'mins': 4516,
 'but': 1594,
 'had': 3312,
 'to': 6944,
 'stop': 6504,
 'somewhere': 6319,
 'first': 2904,
 'always': 941,
 'looking': 4216,
 'for': 2969,
 'an': 966,
 'excuse': 2731,
 'be': 1287,
 'in': 3659,
 'the': 6832,
 'city': 1841,
 'love': 4243,
 'wine': 7540,
 'dine': 2357,
 'my': 4682,
 'lady': 4010,
 '10': 258,
 'min': 4503,
 'later': 4045,
 'yeah': 7688,
 'that': 6827,
 'what': 7487,
 'thought': 6877,
 'lemme': 4091,
 'know': 3979,
 'if': 3624,
 'anything': 1010,
 'goin': 3192,
 'on': 4951,
 'life': 4118,
 'means': 4434,
 'lot': 4231,
 'me': 4427,
 'not': 4845,
 'because': 1296,
 'people': 5156,
 'world': 7609,
 'calls': 1640,
 'them': 6840,
 'friends': 3036,
 'call': 1626,
 'ge': 3120,
 'none': 4827,
 'nowhere': 4861,
 'ikno': 3632,
 'doesdiscount': 2417,
 'shitinnit': 6106,
 'ic': 3603,
 'there': 6845,
 'are': 1059,
 'lotta': 4235,
 'c

In [59]:
x_train_np= x_train_cv.toarray()
x_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4457, 7767))

In [60]:
np.where(x_train_np[0]!=0)

(array([ 907,  970,  988, 1824, 4591, 4745, 7450]),)

In [61]:
x_train[0:4]

979     Another month. I need chocolate weed and alcohol.
3014     &lt;#&gt;  mins but i had to stop somewhere f...
3259    I'm always looking for an excuse to be in the ...
1743                     I love to wine and dine my lady!
Name: v2, dtype: str

In [68]:
#### Naive Bayes classifier
model =MultinomialNB()
model.fit(x_train_cv, y_train)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
Name,Type,Value
"class_count_ class_count_: ndarray of shape (n_classes,)Number of samples encountered for each class during fitting. Thisvalue is weighted by the sample weight when provided.","ndarray[float64](2,)","[3831., 626.]"
"class_log_prior_ class_log_prior_: ndarray of shape (n_classes,)Smoothed empirical log probability for each class.","ndarray[float64](2,)","[-0.15,-1.96]"
"classes_ classes_: ndarray of shape (n_classes,)Class labels known to the classifier","ndarray[int64](2,)","[0,1]"
"feature_count_ feature_count_: ndarray of shape (n_classes, n_features)Number of samples encountered for each (class, feature)during fitting. This value is weighted by the sample weight whenprovided.","ndarray[float64](2, 7767)","[[ 0., 0., 1.,..., 0., 7., 1.], [ 9.,24., 0.,..., 1., 0., 0.]]"
"feature_log_prob_ feature_log_prob_: ndarray of shape (n_classes, n_features)Empirical log probability of featuresgiven a class, ``P(x_i|y)``.","ndarray[float64](2, 7767)","[[-10.96,-10.96,-10.27,...,-10.96, -8.88,-10.27], [ -7.72, -6.8 ,-10.02,..., -9.32,-10.02,-10.02]]"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,7767


In [70]:
y_pred= model. predict(x_test_cv)

In [74]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       994
           1       0.98      0.93      0.96       121

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



### Test On a random dataset

In [83]:
message=("50% off")


In [87]:
message_cnt= v.transform([message])
model.predict(message_cnt)

array([0])